version: '3'

tasks:
  build:
    desc: Build Docker image
    cmds:
      - docker build -t unicorn-roulette:latest .

  run:
    desc: Run the container
    cmds:
      - docker run -d -p 80:80 --name unicorn-roulette unicorn-roulette:latest

  stop:
    desc: Stop and remove the container
    cmds:
      - docker stop unicorn-roulette || true
      - docker rm unicorn-roulette || true

  clean:
    desc: Remove the Docker image
    cmds:
      - task: stop
      - docker rmi unicorn-roulette:latest || true

  all:
    desc: Clean, build, and run
    cmds:
      - task: clean
      - task: build
      - task: run